# Generated by Django 6.1.1 on 2026-09-27 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('min_limit', models.FloatField(blank=True, null=True)),
                ('max_limit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=64, unique=True)),
                ('sample_type', models.CharField(max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('LOGGED', 'Logged In'), ('IN_PROGRESS', 'Testing In Progress'), ('COMPLETED', 'Completed'), ('DISPOSED', 'Disposed')], default='LOGGED', max_length=20)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('PASS', 'In Specification (Pass)'), ('OOS', 'Out of Specification (Fail)')], default='PENDING', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.sample')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.testdefinition')),
            ],
        ),
    ]
