# Generated by Django 6.1.1 on 2026-09-27 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='batch_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_logged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sample',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('LOGGED', 'Logged'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='LOGGED', max_length=20),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='unit',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('OOS', 'Out of Specification')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lab.testdefinition'),
        ),
    ]
