# Generated by Django 6.1.1 on 2026-09-27 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_audittrail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('last_calibrated', models.DateField()),
                ('calibration_due', models.DateField()),
                ('status', models.CharField(choices=[('CALIBRATED', 'Calibrated & In Service'), ('MAINTENANCE', 'Under Maintenance'), ('EXPIRED', 'Calibration Expired / Out of Service')], default='CALIBRATED', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.instrument'),
        ),
        migrations.CreateModel(
            name='StabilityStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_code', models.CharField(max_length=50, unique=True)),
                ('storage_condition', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('protocol_reference', models.CharField(max_length=100)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stability_studies', to='lab.sample')),
            ],
        ),
        migrations.CreateModel(
            name='StabilityTimepoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_name', models.CharField(max_length=50)),
                ('scheduled_date', models.DateField()),
                ('actual_pull_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PULLED', 'Pulled from Chamber'), ('TESTED', 'Testing Completed')], default='SCHEDULED', max_length=20)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timepoints', to='lab.stabilitystudy')),
            ],
        ),
    ]
