# Generated by Django 6.1.1 on 2026-09-27 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_instrument_alter_testdefinition_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='qa_disposition_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_released', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sample',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('LOGGED', 'Logged'), ('IN_PROGRESS', 'In Testing / In Progress'), ('UNDER_REVIEW', 'Under Technical Review'), ('OOS_INVESTIGATION', 'Phase I OOS Investigation'), ('RELEASED', 'QA Released / Approved'), ('REJECTED', 'QA Rejected')], default='LOGGED', max_length=30),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=60)),
                ('record_reference', models.CharField(max_length=120)),
                ('meaning', models.CharField(choices=[('AUTHORED', 'I authored / entered this data'), ('REVIEWED', 'I have technical review oversight (Peer Review)'), ('APPROVED', 'I approve and release this disposition (QA Release)'), ('OOS_INITIATED', 'I initiated this formal OOS investigation'), ('OOS_CLOSED', 'I approve and close this OOS investigation')], max_length=40)),
                ('signer_full_name', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OOSInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_standard_prep', models.BooleanField(default=False, verbose_name='Standard & Reagents Valid & Checked?')),
                ('checklist_instrument_param', models.BooleanField(default=False, verbose_name='Instrument Calibration & Column Checked?')),
                ('checklist_system_suitability', models.BooleanField(default=False, verbose_name='System Suitability Passed?')),
                ('checklist_sample_dilution', models.BooleanField(default=False, verbose_name='Sample Dilution & Balance Confirmed?')),
                ('root_cause_analysis', models.TextField(blank=True, null=True)),
                ('capa_action', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Phase I Investigation Open'), ('LAB_ERROR_CONFIRMED', 'Assignable Cause: Laboratory Error'), ('MANUFACTURING_CONFIRMED', 'True OOS: Manufacturing Flaw'), ('CLOSED', 'Closed & Disposition Decided')], default='OPEN', max_length=30)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oos_closed', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oos_initiated', to=settings.AUTH_USER_MODEL)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oos_investigation', to='lab.sample')),
            ],
        ),
        migrations.CreateModel(
            name='UniversalAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=60)),
                ('entity_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('CREATE', 'Record Creation'), ('UPDATE', 'Modification / Change'), ('DELETE', 'Deletion / Deactivation'), ('SIGN', 'Electronic Signature')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AuditTrail',
        ),
    ]
