# Generated by Django 6.1.1 on 2026-09-27 16:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_sample_qa_disposition_notes_sample_released_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_tag', models.CharField(max_length=60, unique=True)),
                ('instrument_name', models.CharField(max_length=150)),
                ('instrument_type', models.CharField(choices=[('HPLC', 'High-Performance Liquid Chromatography (HPLC)'), ('UPLC', 'Ultra-Performance Liquid Chromatography (UPLC)'), ('GC', 'Gas Chromatography (GC)'), ('BALANCE', 'Analytical Balance (RS-232 / Mettler-Toledo/Sartorius)'), ('PH_METER', 'Digital pH Meter'), ('TOC', 'Total Organic Carbon Analyzer (TOC)'), ('TIMO', 'Automated Titrator (TIMO)'), ('ELN', 'Electronic Lab Notebook Interface (ELN API)')], max_length=30)),
                ('interface_type', models.CharField(choices=[('TCPIP', 'Direct TCP/IP Network Socket'), ('RS232', 'RS-232 Serial Port (COM)'), ('REST_API', 'RESTful API / Webhook (Waters Empower / OpenLab)'), ('FILE_WATCH', 'File Drop / Hotfolder Watcher')], max_length=20)),
                ('ip_or_com_port', models.CharField(help_text='e.g. 192.168.1.105:8000 or COM3', max_length=100)),
                ('baud_rate', models.IntegerField(blank=True, default=9600, help_text='For RS232 connections', null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Connected & Ready'), ('STREAMING', 'Acquiring / Reading Live'), ('OFFLINE', 'Disconnected / Unreachable'), ('ERROR', 'Interface Communication Fault')], default='OFFLINE', max_length=20)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentDataFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.TextField(help_text='Raw ASCII, CSV, JSON, or CDS peak report')),
                ('extracted_parameter', models.CharField(max_length=100)),
                ('extracted_value', models.FloatField(blank=True, null=True)),
                ('received_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_feeds', to='lab.instrumentconnector')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.sample')),
            ],
        ),
    ]
