# Generated by Django 6.1.1 on 2026-09-28 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_department_jobtype_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('material_type', models.CharField(choices=[('API', 'Active Pharmaceutical Ingredient (API)'), ('EXCIPIENT', 'Raw Material / Excipient'), ('PRIMARY_PKG', 'Primary Packaging Material'), ('SECONDARY_PKG', 'Secondary Packaging')], max_length=30)),
                ('cas_number', models.CharField(blank=True, help_text='CAS Registry Number', max_length=40, null=True)),
                ('grade', models.CharField(default='USP/NF/EP/BP', max_length=40)),
                ('retest_period_months', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('generic_name', models.CharField(max_length=150)),
                ('brand_name', models.CharField(max_length=150)),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('INJECTION', 'Liquid Injectable / Vial'), ('ORAL_LIQUID', 'Oral Liquid / Syrup'), ('TOPICAL', 'Ointment / Cream')], max_length=60)),
                ('strength', models.CharField(help_text='e.g. 500 mg, 10 mg/mL', max_length=60)),
                ('shelf_life_months', models.IntegerField(default=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('OBSOLETE', 'Obsolete')], default='APPROVED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StorageCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('temperature_range', models.CharField(help_text='e.g. 15°C - 25°C or 2°C - 8°C', max_length=60)),
                ('humidity_range', models.CharField(blank=True, help_text='e.g. 60% ± 5% RH', max_length=60, null=True)),
                ('light_protection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('supplier_type', models.CharField(choices=[('MANUFACTURER', 'Actual Manufacturer'), ('DISTRIBUTOR', 'Approved Distributor'), ('SERVICE_LAB', 'Contract Testing Laboratory')], default='MANUFACTURER', max_length=30)),
                ('country', models.CharField(default='India', max_length=60)),
                ('qualification_status', models.CharField(choices=[('QUALIFIED', 'Fully Qualified & Approved'), ('CONDITIONAL', 'Conditionally Approved'), ('DISQUALIFIED', 'Disqualified / Blocked')], default='QUALIFIED', max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_code', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('technique', models.CharField(choices=[('HPLC', 'High Performance Liquid Chromatography (HPLC)'), ('GC', 'Gas Chromatography (GC)'), ('UV', 'UV-Vis Spectrophotometry'), ('TITRATION', 'Potentiometric / Volumetric Titration'), ('DISSOLUTION', 'Dissolution Testing (USP App I/II)'), ('PHYSICAL', 'Physical Appearance & Hardness/Friability'), ('MICRO', 'Microbial Limit Testing')], max_length=60)),
                ('compendial_source', models.CharField(default='In-House / USP', help_text='USP, Ph. Eur., IP, BP, or In-House', max_length=50)),
                ('sop_reference', models.CharField(help_text='SOP-QC-XXX', max_length=100)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('validation_status', models.CharField(choices=[('VALIDATED', 'Validated Protocol'), ('VERIFIED', 'Compendial Verified'), ('TRANSFERRED', 'Method Transferred')], default='VALIDATED', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Assay/Potency', 'Assay/Potency'), ('Mass/Weight', 'Mass/Weight'), ('Volume', 'Volume'), ('Physical', 'Physical (pH, Viscosity, Density)'), ('Impurity/Trace', 'Impurity/Trace (ppm, ppb, %)'), ('General', 'General')], default='General', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='baud_rate',
            field=models.IntegerField(blank=True, default=9600, null=True),
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='ip_or_com_port',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumentdatafeed',
            name='raw_payload',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oosinvestigation',
            name='checklist_instrument_param',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oosinvestigation',
            name='checklist_sample_dilution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oosinvestigation',
            name='checklist_standard_prep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='oosinvestigation',
            name='checklist_system_suitability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_theme',
            field=models.CharField(default='deep-navy', max_length=20),
        ),
        migrations.CreateModel(
            name='SpecificationHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_number', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('spec_type', models.CharField(choices=[('RELEASE_FG', 'Finished Product Release Specification'), ('STABILITY_FG', 'Finished Product Stability Specification'), ('RAW_MATERIAL', 'Raw Material / API Specification'), ('IN_PROCESS', 'In-Process Quality Specification')], max_length=30)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'Under Technical Review'), ('APPROVED', 'Effective / Approved'), ('SUPERSEDED', 'Superseded / Retired')], default='APPROVED', max_length=20)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='storage_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.storagecondition'),
        ),
        migrations.AddField(
            model_name='material',
            name='storage_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.storagecondition'),
        ),
        migrations.AddField(
            model_name='material',
            name='primary_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.supplier'),
        ),
        migrations.AddField(
            model_name='testdefinition',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.testmethod'),
        ),
        migrations.CreateModel(
            name='SpecificationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_parameter', models.CharField(max_length=100)),
                ('evaluation_type', models.CharField(choices=[('NUMERIC_RANGE', 'Numeric Min / Max Range'), ('MIN_ONLY', 'Minimum Limit Only (>=)'), ('MAX_ONLY', 'Maximum Limit Only (<=)'), ('TEXT_EQUAL', 'Exact Text / Visual Inspection')], default='NUMERIC_RANGE', max_length=30)),
                ('min_limit', models.FloatField(blank=True, null=True)),
                ('max_limit', models.FloatField(blank=True, null=True)),
                ('text_specification', models.CharField(blank=True, help_text="e.g. 'White to off-white round tablet'", max_length=200, null=True)),
                ('decimal_places', models.IntegerField(default=1)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='lab.specificationheader')),
                ('test_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.testmethod')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.unitofmeasure')),
            ],
        ),
    ]
