# Generated by Django 6.1.1 on 2026-09-29 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_material_product_storagecondition_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('AMBIENT', 'Controlled Ambient (15-25°C)'), ('REFRIGERATED', 'Cold Room / 2-8°C'), ('FREEZER_20', 'Deep Freezer (-20°C)'), ('FREEZER_80', 'Ultra-Low Freezer (-80°C)'), ('STABILITY_CHAMBER', 'Stability Chamber'), ('DISPOSAL_BIN', 'Hazardous Waste / Disposal Queue')], default='AMBIENT', max_length=30)),
                ('capacity_units', models.IntegerField(default=100)),
                ('is_operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='specificationheader',
            name='review_date',
        ),
        migrations.RemoveField(
            model_name='specificationheader',
            name='spec_type',
        ),
        migrations.AddField(
            model_name='sample',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.material'),
        ),
        migrations.AddField(
            model_name='sample',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Routine (Standard TAT)'), ('URGENT', 'Priority / Urgent'), ('CRITICAL', 'Emergency / Line Clearance')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.product'),
        ),
        migrations.AddField(
            model_name='sample',
            name='purpose',
            field=models.CharField(choices=[('RELEASE', 'Commercial Batch Release'), ('RETEST', 'Periodic Material Retest'), ('INVESTIGATION', 'OOS / Deviation Investigation'), ('VALIDATION', 'Process / Cleaning Validation'), ('SURVEILLANCE', 'Routine Monitoring')], default='RELEASE', max_length=40),
        ),
        migrations.AddField(
            model_name='sample',
            name='quantity_collected',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='sample',
            name='quantity_unit',
            field=models.CharField(default='Units', max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.specificationheader'),
        ),
        migrations.AlterField(
            model_name='electronicsignature',
            name='meaning',
            field=models.CharField(choices=[('AUTHORED', 'I authored / entered this data'), ('REVIEWED', 'I have technical review oversight (Peer Review)'), ('APPROVED', 'I approve and release this disposition (QA Release)'), ('OOS_INITIATED', 'I initiated this formal OOS investigation'), ('OOS_CLOSED', 'I approve and close this OOS investigation'), ('HOLD_PLACED', 'I authorized placing a quality hold'), ('HOLD_RELEASED', 'I authorized releasing the quality hold')], max_length=40),
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='instrument_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='interface_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='status',
            field=models.CharField(default='OFFLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='cas_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(default='TABLET', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='strength',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('FINISHED_PRODUCT', 'Finished Product (Commercial/Clinical)'), ('RAW_MATERIAL', 'Raw Material / API'), ('PACKAGING', 'Packaging Material (Primary/Secondary)'), ('IN_PROCESS', 'In-Process Control (IPC)'), ('WATER', 'Pharmaceutical Water (Purified/WFI)'), ('ENVIRONMENTAL', 'Environmental Monitoring (EM)'), ('STABILITY', 'Stability Study Pull')], default='FINISHED_PRODUCT', max_length=40),
        ),
        migrations.AlterField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('LOGGED', 'Logged & Accessioned'), ('COLLECTED', 'Sample Collected / Received'), ('IN_PROGRESS', 'In Testing / Analytical Stage'), ('UNDER_REVIEW', 'Under Peer Review'), ('OOS_INVESTIGATION', 'Phase I OOS Investigation'), ('RELEASED', 'QA Released / Approved'), ('REJECTED', 'QA Rejected'), ('HOLD', 'Quality Administrative Hold')], default='LOGGED', max_length=30),
        ),
        migrations.AlterField(
            model_name='specificationheader',
            name='status',
            field=models.CharField(default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='stabilitytimepoint',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='storagecondition',
            name='humidity_range',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='storagecondition',
            name='temperature_range',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='qualification_status',
            field=models.CharField(default='QUALIFIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(default='MANUFACTURER', max_length=30),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='compendial_source',
            field=models.CharField(default='USP', max_length=50),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='sop_reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='technique',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='validation_status',
            field=models.CharField(default='VALIDATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='category',
            field=models.CharField(default='General', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='ANALYST', max_length=30),
        ),
        migrations.CreateModel(
            name='EnvironmentalSampleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(help_text='e.g. Cleanroom B-102', max_length=100)),
                ('cleanroom_grade', models.CharField(choices=[('GRADE_A', 'Grade A (Class 100 / ISO 5)'), ('GRADE_B', 'Grade B (ISO 5 at rest / ISO 7 operational)'), ('GRADE_C', 'Grade C (Class 10,000 / ISO 7)'), ('GRADE_D', 'Grade D (Class 100,000 / ISO 8)'), ('CNC', 'Controlled Non-Classified (CNC)')], default='GRADE_B', max_length=20)),
                ('monitoring_method', models.CharField(choices=[('ACTIVE_AIR', 'Active Air Sampling (Sieve)'), ('SETTLE_PLATE', 'Passive Settle Plate (4 Hours)'), ('SURFACE_CONTACT', 'Surface Contact (RODAC Plate)'), ('SWAB', 'Surface Swab Sampling'), ('PARTICLE_COUNTER', 'Non-Viable Particle Count')], default='SETTLE_PLATE', max_length=40)),
                ('exposure_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('exposure_end', models.DateTimeField(blank=True, null=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_detail', to='lab.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('OOS_INVESTIGATION', 'Pending OOS Investigation'), ('DEVIATION', 'Linked Production / Lab Deviation'), ('AUDIT_FINDING', 'QA Regulatory Hold'), ('TEMPERATURE_EXCURSION', 'Cold-Chain / Chamber Excursion')], default='OOS_INVESTIGATION', max_length=40)),
                ('qms_reference', models.CharField(help_text='e.g. DEV-2026-089, OOS-2026-012', max_length=100)),
                ('reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_justification', models.TextField(blank=True, null=True)),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds_placed', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds_released', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='lab.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SourceLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_lot_number', models.CharField(max_length=100, unique=True)),
                ('supplier_lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('retest_date', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='source_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.sourcelot'),
        ),
        migrations.CreateModel(
            name='RetentionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESERVE', 'Official Batch Reserve Sample (Finished Goods)'), ('REFERENCE', 'Starting Material Reference Sample'), ('STABILITY', 'Formal Stability Retain')], default='RESERVE', max_length=30)),
                ('retained_quantity', models.FloatField(default=1.0)),
                ('quantity_unit', models.CharField(default='Packs', max_length=20)),
                ('retain_until_date', models.DateField(help_text='Expiry + 1 year (or dossier commitment)')),
                ('is_disposed', models.BooleanField(default=False)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention', to='lab.sample')),
                ('assigned_storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seal_intact', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_received', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_released', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='lab.sample')),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='lab.storagelocation')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='lab.storagelocation')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='current_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.storagelocation'),
        ),
        migrations.CreateModel(
            name='WaterSampleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_point', models.CharField(help_text='e.g. Loop 1 Point 14 (SP-14)', max_length=100)),
                ('water_grade', models.CharField(choices=[('POTABLE', 'Potable Water'), ('PURIFIED', 'Purified Water (USP/EP)'), ('WFI', 'Water for Injection (WFI)'), ('PURE_STEAM', 'Pure Steam Condensate')], default='PURIFIED', max_length=40)),
                ('sampling_mode', models.CharField(choices=[('PRE_FLUSH', 'Pre-Flush / First Catch'), ('POST_FLUSH', 'Post-Flush (Routine)'), ('AS_USED', 'As-Used Manufacturing Point')], default='POST_FLUSH', max_length=40)),
                ('flush_duration_minutes', models.IntegerField(default=5)),
                ('sample_temperature_celsius', models.FloatField(default=22.0)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='water_detail', to='lab.sample')),
            ],
        ),
    ]
