# Generated by Django 6.1.1 on 2026-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_storagelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationheader',
            name='spec_type',
            field=models.CharField(choices=[('RELEASE_FG', 'Finished Product Release Specification'), ('STABILITY_FG', 'Finished Product Stability Specification'), ('RAW_MATERIAL', 'Raw Material / API Specification'), ('IN_PROCESS', 'In-Process Quality Specification')], default='RELEASE_FG', max_length=30),
        ),
        migrations.AlterField(
            model_name='environmentalsampledetail',
            name='room_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='instrument_type',
            field=models.CharField(choices=[('HPLC', 'High-Performance Liquid Chromatography (HPLC)'), ('UPLC', 'Ultra-Performance Liquid Chromatography (UPLC)'), ('GC', 'Gas Chromatography (GC)'), ('BALANCE', 'Analytical Balance (RS-232 / Mettler-Toledo/Sartorius)'), ('PH_METER', 'Digital pH Meter'), ('TOC', 'Total Organic Carbon Analyzer (TOC)'), ('TIMO', 'Automated Titrator (TIMO)'), ('ELN', 'Electronic Lab Notebook Interface (ELN API)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='interface_type',
            field=models.CharField(choices=[('TCPIP', 'Direct TCP/IP Network Socket'), ('RS232', 'RS-232 Serial Port (COM)'), ('REST_API', 'RESTful API / Webhook (Waters Empower / OpenLab)'), ('FILE_WATCH', 'File Drop / Hotfolder Watcher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='instrumentconnector',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Connected & Ready'), ('STREAMING', 'Acquiring / Reading Live'), ('OFFLINE', 'Disconnected / Unreachable'), ('ERROR', 'Interface Communication Fault')], default='OFFLINE', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('API', 'Active Pharmaceutical Ingredient (API)'), ('EXCIPIENT', 'Raw Material / Excipient'), ('PRIMARY_PKG', 'Primary Packaging Material'), ('SECONDARY_PKG', 'Secondary Packaging')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('INJECTION', 'Liquid Injectable / Vial'), ('ORAL_LIQUID', 'Oral Liquid / Syrup'), ('TOPICAL', 'Ointment / Cream')], default='TABLET', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('OBSOLETE', 'Obsolete')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='retentionassignment',
            name='retain_until_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='samplehold',
            name='qms_reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specificationheader',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'Under Technical Review'), ('APPROVED', 'Effective / Approved'), ('SUPERSEDED', 'Superseded / Retired')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='specificationline',
            name='text_specification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stabilitytimepoint',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PULLED', 'Pulled from Chamber'), ('TESTED', 'Testing Completed')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='qualification_status',
            field=models.CharField(choices=[('QUALIFIED', 'Fully Qualified & Approved'), ('CONDITIONAL', 'Conditionally Approved'), ('DISQUALIFIED', 'Disqualified / Blocked')], default='QUALIFIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('MANUFACTURER', 'Actual Manufacturer'), ('DISTRIBUTOR', 'Approved Distributor'), ('SERVICE_LAB', 'Contract Testing Laboratory')], default='MANUFACTURER', max_length=30),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='technique',
            field=models.CharField(choices=[('HPLC', 'High Performance Liquid Chromatography (HPLC)'), ('GC', 'Gas Chromatography (GC)'), ('UV', 'UV-Vis Spectrophotometry'), ('TITRATION', 'Potentiometric / Volumetric Titration'), ('DISSOLUTION', 'Dissolution Testing (USP App I/II)'), ('PHYSICAL', 'Physical Appearance & Hardness/Friability'), ('MICRO', 'Microbial Limit Testing')], max_length=60),
        ),
        migrations.AlterField(
            model_name='testmethod',
            name='validation_status',
            field=models.CharField(choices=[('VALIDATED', 'Validated Protocol'), ('VERIFIED', 'Compendial Verified'), ('TRANSFERRED', 'Method Transferred')], default='VALIDATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='category',
            field=models.CharField(choices=[('Assay/Potency', 'Assay/Potency'), ('Mass/Weight', 'Mass/Weight'), ('Volume', 'Volume'), ('Physical', 'Physical (pH, Viscosity, Density)'), ('Impurity/Trace', 'Impurity/Trace (ppm, ppb, %)'), ('General', 'General')], default='General', max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ANALYST', 'QC Analyst (Data Entry)'), ('REVIEWER', 'Technical Peer Reviewer'), ('QA_MANAGER', 'QA Release Authority'), ('SYSTEM_ADMIN', 'LIMS System Administrator')], default='ANALYST', max_length=30),
        ),
        migrations.AlterField(
            model_name='watersampledetail',
            name='sampling_point',
            field=models.CharField(max_length=100),
        ),
    ]
